### ISSUE TITLE
follow up to google calendar

### ISSUE THREAD

**Issue by evelien** [amulyakhare/Thunderbird-Follow-Up-Extension#7]
would it be possible to choose a google calendar (which I connected to my lightning) as default calendar for follow up?

**Comment by alanbarker** [comment]
Evelien, I have connected it to my Google calendar and although i have not extensively tested it, it seems to work OK.

To do so you need to change the configuration parameter that Follow-Up uses to find its "Follow-Up" calendar. You just set this to the name of your google-synched calendar and you're good to go.

from Thunderbird main menu:  
1) Tools -> Options -> Advanced (Tab)-> 
2) Click the Config Editor button (accepting the warning)
3) In the filter bar of the config editor enter: "extensions.follow_up_ext.calname" (without quotes)
4) Double click the single row that is returned
5) Enter the name of your Google synched calendar (as its displayed in Lightning, be careful with uppercase and lowercase letters) and click OK.
6) Close the Config editor.

You should now see that Event entries are placed into that calendar. 

AB.

**Comment by evelien** [comment]
it's working (after a restart of thunderbird). Thanks!
